@startuml "usecases"

title "Негативный сценарий 9. Компрометация системы орошения.\n Замена парметров смешивания химических элементов. Нарушение ЦБ 2, 3"

participant "Система планирования выращивания" as growing_manager_system
participant "2. Связь с базой данных сортов помидоров" as tomato_db_connection
participant "1. Система управления теплицей" as greenhouse_manager_system
participant "3. Система искусственного освещения" as lighting_system
participant "4. Климат-контроль" as climate_control
participant "5. Система мониторинга зрелости" as maturity_monitoring_system
participant "6. Система орошения" as irrigation_system #red
participant "7. Система сборки урожая" as harvest_system
participant "8. Система посадки семян" as seed_planting_system

autonumber

growing_manager_system -> greenhouse_manager_system: Отправка запроса на выращивание\n в свободной теплице с идентификатором сорта

greenhouse_manager_system -> tomato_db_connection: Запрос на получение параметров среды\n по идентификатору сорта
tomato_db_connection -> greenhouse_manager_system: Получение параметров

greenhouse_manager_system -> seed_planting_system: Посадка семян
seed_planting_system -> greenhouse_manager_system: Семена посажены

greenhouse_manager_system -> climate_control: Передача параметров необходимого климата
climate_control -> climate_control: Проверка текущих параметров с необходимыми\n и изменение если необходимо

greenhouse_manager_system -> lighting_system: Передача параметров необходимого освещения
lighting_system -> lighting_system: Проверка текущих параметров с необходимыми\n и изменение если необходимо

greenhouse_manager_system -> irrigation_system: Передача параметров необходимого орошения
irrigation_system -[#red]> irrigation_system: Проверка текущих параметров с необходимыми\n и изменение если необходимо\n(параметры химикатов для смешивания были изменены)

maturity_monitoring_system -> maturity_monitoring_system: Проверка зрелости плодов
maturity_monitoring_system -> greenhouse_manager_system: Плоды созрели

greenhouse_manager_system -> harvest_system: Запрос на сборку плодов
harvest_system -> greenhouse_manager_system: Плоды собраны

greenhouse_manager_system -> growing_manager_system: Продукция на складе

@enduml